"""SynchronizedFrame — camera frame paired with a telemetry snapshot.

The Frame Synchronizer produces one SynchronizedFrame per processed camera
tick.  Every downstream stage (VARI, Threshold, Morphology, Region Extractor)
reads from this single immutable snapshot so that all stages operate on the
same frame identity and telemetry coordinates.

Fields
------
frame_uuid       UUID4 string, unique per frame, generated by the synchronizer.
frame_number     Monotonically increasing integer starting from 0 for this
                 session.  Resets when a new session starts.
timestamp        time.monotonic() value at the moment the frame was captured.
                 Use for inter-frame timing only — not wall-clock.
image            BGR ndarray as returned by cv2 / CameraService.get_frame().
                 The array is owned by this dataclass; callers must not mutate it.
lat              Drone latitude in decimal degrees at frame capture time.
lon              Drone longitude in decimal degrees at frame capture time.
alt              Drone altitude in metres (relative) at frame capture time.
heading          Compass heading in degrees (0–360) at frame capture time.
yaw              Yaw angle in degrees from ATTITUDE message.
ground_speed     Ground speed in m/s at frame capture time.
mission_progress Mission progress as a fraction in [0.0, 1.0].
                 0.0 when no mission is active.
waypoint         Current target waypoint sequence number.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np


@dataclass
class SynchronizedFrame:
    """Camera frame paired with a telemetry snapshot.

    Instances are created exclusively by FrameSynchronizer; treat as immutable
    after construction.
    """

    frame_uuid: str
    frame_number: int
    timestamp: float

    # Camera image (BGR, uint8)
    image: np.ndarray = field(repr=False)

    # Telemetry at capture time
    lat: float = 0.0
    lon: float = 0.0
    alt: float = 0.0
    heading: float = 0.0
    yaw: float = 0.0
    ground_speed: float = 0.0
    mission_progress: float = 0.0
    waypoint: int = 0
